// react/src/components/SpeechRecognition.jsx
import styles from "./SpeechRecognition.module.css";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

function SpeechRecognition() {
  const [inputValue, setInputValue] = useState("");
  const navigate = useNavigate();

  function navigateToResults() {
    navigate(`/search/${inputValue}`);
  }

  function handleKeyPress(event) {
    if (event.key === "Enter") {
      navigateToResults();
    }
  }

  return (
    <div className={styles.speechContainer}>
      <>
        <div className={styles.chatDiv}>
          <h3 className={styles.chatHeader}>
            Which word do you want to practice?
          </h3>
        </div>
      </>
      <div className={styles.inputDiv}>
        <input
          type="text"
          className={styles.input}
          placeholder="Write your word here"
          value={inputValue}
          onChange={(e) => {
            setInputValue(e.target.value);
          }}
          onKeyDown={handleKeyPress}
        ></input>
      </div>
    </div>
  );
}

export default SpeechRecognition;

// angular/src/app/components/speech-recognition/speech-recognition.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-speech-recognition',
  standalone: true,
  imports: [],
  templateUrl: './speech-recognition.component.html',
  styleUrl: './speech-recognition.component.css',
})
export class SpeechRecognitionComponent {
  inputValue: string = '';

  constructor(private router: Router) {}

  navigateToResults() {
    this.router.navigate([`/search/${this.inputValue}`]); // Navigate to results page
  }

  handleKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.navigateToResults();
    }
  }

  handleInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.inputValue = target.value;
  }
}

<div class="speech-container">
  <div class="chat-div">
    <h3 class="chat-header">Which word do you want to practice?</h3>
  </div>
  <div class="input-div">
    <input
      type="text"
      class="input"
      placeholder="Write your word here"
      (input)="handleInput($event)"
      (keydown)="handleKeyPress($event)"
    />
  </div>
</div>
