// react/src/pages/SearchResults.jsx
import "./SearchResult.css";
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import axios from "axios";

function SearchResults() {
  const { word } = useParams();
  const [wordData, setWordData] = useState(null);
  const navigate = useNavigate();

  async function fetchWordData() {
    try {
      const response = await axios.post("http://localhost:5000/fetchword", {
        userInput: word,
      });
      setWordData(response.data);
    } catch (error) {
      console.error("Error fetching word data:", error);
      setWordData(null);
    }
  }

  function handlePracticeClick(word, phonetic) {
    navigate(`/practice`, { state: { word, phonetic } });
  }

  useEffect(() => {
    fetchWordData();
  }, [word]);

  return (
    <div className="results-div">
      {wordData && (
        <>
          {wordData.map((word, index) => (
            <div key={index}>
              <div className="word-button">
                <h3 className="word-header">{word.word}</h3>
                <button
                  onClick={() => handlePracticeClick(word.word, word.phonetic)}
                  className="btn"
                >
                  Practice this word
                </button>
              </div>
              <span className="phonetic">{word.phonetic}</span>
              {word.meanings.map((meaning, index) => (
                <div key={index} className="definitions">
                  <h4 className="part-of-speech">{meaning.partOfSpeech}</h4>
                  {meaning.definitions.map((definition, index) => (
                    <div key={index} className="definition-div">
                      <span className="index-span">{index + 1}</span>
                      <p className="definition">{definition.definition}</p>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          ))}
        </>
      )}
    </div>
  );
}

export default SearchResults;

// angular/src/app/pages/search-results/search-results.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-search-results',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './search-results.component.html',
  styleUrl: './search-results.component.css',
})
export class SearchResultsComponent {
  word: string | null = null;
  wordData: any = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private http: HttpClient
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      this.word = params.get('word');
      this.fetchWordData();
    });
  }

  fetchWordData(): void {
    if (this.word) {
      this.http
        .post('http://localhost:5000/fetchword', { userInput: this.word })
        .subscribe(
          (response: any) => {
            this.wordData = response;
          },
          (error: any) => {
            console.error('Error fetching word data:', error);
            this.wordData = null;
          }
        );
    } else {
      console.error('Word is null, cannot fetch data');
    }
  }

  handlePracticeClick(word: string, phonetic: string): void {
    this.router.navigate(['/practice'], { state: { word, phonetic } });
  }
}

<div class="results-div">
  <ng-container *ngIf="wordData">
    <ng-container *ngFor="let word of wordData; let wordIndex = index">
      <div class="word-button">
        <h3 class="word-header">{{ word.word }}</h3>
        <button
          (click)="handlePracticeClick(word.word, word.phonetic)"
          class="btn"
        >
          Practice this word
        </button>
      </div>
      <span class="phonetic">{{ word.phonetic }}</span>
      <div
        *ngFor="let meaning of word.meanings; let meaningIndex = index"
        class="definitions"
      >
        <!-- <div class="definitions"> -->
        <h4 class="part-of-speech">{{ meaning.partOfSpeech }}</h4>
        <div
          *ngFor="let definition of meaning.definitions; let defIndex = index"
          class="definition-div"
        >
          <span class="index-span">{{ defIndex + 1 }}</span>
          <p class="definition">{{ definition.definition }}</p>
        </div>
        <!-- </div> -->
      </div>
    </ng-container>
  </ng-container>
</div>
