// angular/src/app/pages/practice-word/practice-word.component.ts
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-practice-word',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './practice-word.component.html',
  styleUrl: './practice-word.component.css',
})
export class PracticeWordComponent {
  word: string = '';
  phonetic: string = '';
  instructions: string = '';
  isRecording: boolean = false;
  transcript: string = '';
  feedback: string = '';
  recognitionRef: any = null;

  constructor(private router: Router, private http: HttpClient) {}

  ngOnInit(): void {
    // GET WORD AND PHONETIC
    const state = history.state as { word: string; phonetic: string };

    this.word = state?.word;
    this.phonetic = state?.phonetic;

    console.log(this.instructions);

    // GET INSTRUCTIONS
    if (this.phonetic) {
      this.getInstruction(this.phonetic);
    }

    console.log(this.instructions);
  }

  // GET INSTRUCTIONS FUNCTION--------------------------------------------------------
  getInstruction(phonetic: string): void {
    this.http
      .post('http://localhost:5000/instructions', { phonetic: phonetic })
      .subscribe(
        (response: any) => {
          this.instructions = response;
        },
        (error: any) => {
          console.error('Error getting instructions:', error);
        }
      );
  }

  // START RECORDING VOICE FUNCTION--------------------------------------------------------
  startRecording(): void {
    console.log('start recording called');

    if (!('webkitSpeechRecognition' in window)) {
      alert('Your browser does not support speech recognition');
      return;
    }

    const recognition = new (window as any).webkitSpeechRecognition();
    this.recognitionRef.current = recognition;

    recognition.lang = 'en-GB';
    recognition.continuous = false;
    recognition.interimResults = false;

    // Event: when recognition starts
    recognition.onstart = () => {
      console.log('Speech recognition started');
      this.isRecording = true;
    };

    // Event: when recognition result is received
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      // this.transcript = transcript;

      this.http
        .post('http://localhost:5000/analyse', {
          recognisedText: transcript,
          expectedWord: this.word,
        })
        .subscribe(
          (response: any) => {
            this.feedback = response.data;
          },
          (error) => {
            console.error('Error comparing phonetics:', error);
          }
        );
    };

    // Event: when recognition ends
    recognition.onend = () => {
      console.log('Speech recognition ended');
      this.isRecording = false;
    };

    // Event: on error
    recognition.onerror = (event: any) => {
      console.error('Speech recognition error:', event.error);
      this.isRecording = false;
    };

    // Start recognition
    recognition.start();
  }

  // STOP RECORDING VOICE FUNCTION--------------------------------------------------------
  stopRecording(): void {
    if (this.recognitionRef.current) {
      this.recognitionRef.current.stop();
    }
  }
}

<div class="practice-div">
  <div *ngIf="word && phonetic" class="speech-container">
    <h1 class="word-title">
      Let's practice how to say: <span class="word">{{ word }}</span>
    </h1>
    <p class="phonetic">
      Phonetic transcription: <strong>{{ phonetic }}</strong>
    </p>
    <p class="instructions">
      <strong>Instructions:</strong> Read the instructions below, and when
      ready, <span class="highlight">press the button</span> to start recording
      and <span class="highlight">pronounce the word aloud</span>.
    </p>
    <p class="instruction-details">{{ instructions }}</p>

    <!-- Button with Microphone for Start Recording  -->
    <button
      [ngClass]="isRecording ? 'recording-button' : 'try-button'"
      (click)="isRecording ? stopRecording() : startRecording()"
    >
      {{ isRecording ? "Stop Recording" : "Start Recording" }}
    </button>

    <div class="feedback-container">
      <p class="transcript">Transcript: {{ transcript }}</p>
      <p
        [ngClass]="feedback.includes('Failed') ? 'error' : 'success'"
        class="feedback"
      >
        {{ feedback }}
      </p>
    </div>
  </div>
</div>

// react/src/pages/PracticeWord.jsx
import { useLocation } from "react-router-dom";
import { useEffect, useState, useRef } from "react";
import axios from "axios";
import styles from "./PracticeWord.module.css";

function PracticeWord() {
  const location = useLocation();
  const { word, phonetic } = location.state || {};
  const [instructions, setInstructions] = useState("");
  const [transcript, setTranscript] = useState("");
  const [feedback, setFeedback] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef(null);

  // GET INSTRUCTIONS FUNCTION--------------------------------------------------------
  async function getInstructions(phonetic) {
    try {
      const response = await axios.post("http://localhost:5000/instructions", {
        phonetic: phonetic,
      });
      setInstructions(response.data);
    } catch (error) {
      console.error("Error getting isntructions:", error);
    }
  }

  // ANALYSE VOICE TRANSCRIPT--------------------------------------------------------
  async function analyse() {
    console.log("start analyse");
    console.log("transcript:", transcript);

    try {
      console.log("before post");
      const response = await axios.post("http://localhost:5000/analyse", {
        recognizedText: transcript,
        expectedWord: word,
      });
      console.log("after post");
      console.log(response.data);
      setFeedback(response.data);
    } catch (error) {
      console.error("Error comparing phonetics:", error);
      setFeedback("Failed to analyse pronunciation");
    }
  }

  // START RECORDING VOICE FUNCTION--------------------------------------------------------
  function startRecording() {
    if (!("webkitSpeechRecognition" in window)) {
      alert("Your browser does not support speech recognition");
      return;
    }

    const recognition = new window.webkitSpeechRecognition();
    recognitionRef.current = recognition;

    recognition.lang = "en-GB";
    recognition.continuous = false;
    recognition.interimResults = false;

    recognition.onstart = () => {
      console.log("Speech recognition started");
      setIsRecording(true);
    };

    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;

      axios
        .post("http://localhost:5000/analyse", {
          recognizedText: transcript,
          expectedWord: word,
        })
        .then((response) => {
          setFeedback(response.data);
        })
        .catch((error) => {
          console.error("Error comparing phonetics:", error);
          setFeedback("Failed to analyse pronunciation");
        });
    };

    recognition.onerror = (event) => {
      console.error("Speech recognition error:", event.error);
      alert(`An error occurred during speech recognition: ${event.error}`);
      setIsRecording(false);
    };

    recognition.onend = () => {
      console.log("Speech recognition ended");
      setIsRecording(false);
    };

    recognition.start();
  }

  // STOP RECORDING VOICE FUNCTION--------------------------------------------------------
  function stopRecording() {
    if (recognitionRef.current) {
      recognitionRef.current.stop();
    }
  }

  // CALL ANALYSE WHEN TRANSCRIPT IS UPDATED
  useEffect(() => {
    if (transcript) {
      analyse();
    }
  }, [transcript]);

  // -----------------------------------------------------------------------------------

  useEffect(() => {
    getInstructions(phonetic);
  }, [phonetic]);

  // -----------------------------------------------------------------------------------

  return (
    <div className={styles.practiceDiv}>
      {word && phonetic ? (
        <div className={styles.speechContainer}>
          <h1 className={styles.wordTitle}>
            Let's practice how to say:{" "}
            <span className={styles.word}>{word}</span>
          </h1>
          <p className={styles.phonetic}>
            Phonetic transcription: <strong>{phonetic}</strong>
          </p>

          <p className={styles.instructions}>
            <strong>Instructions:</strong> Read the instructions below, and when
            ready, <span className={styles.highlight}>press the button</span> to
            start recording and{" "}
            <span className={styles.highlight}>pronounce the word aloud</span>.
          </p>
          <p className={styles.instructionDetails}>{instructions}</p>

          {/* Button with Microphone for Start Recording */}
          <button
            className={isRecording ? styles.recordingButton : styles.tryButton}
            onClick={isRecording ? stopRecording : startRecording}
          >
            {isRecording ? <>Stop Recording</> : <>Start Recording</>}
          </button>

          <div className={styles.feedbackContainer}>
            <p className={styles.transcript}>Transcript: {transcript}</p>
            <p
              className={`${styles.feedback} ${
                feedback.includes("Failed") ? styles.error : styles.success
              }`}
            >
              {feedback}
            </p>
          </div>
        </div>
      ) : (
        <div>
          <p>No data</p>
        </div>
      )}
    </div>
  );
}

export default PracticeWord;
