// angular/src/app/components/navbar/navbar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {
  @Input() isSidebarOpen!: boolean; // Receives the state from the parent
  @Output() toggleSidebar = new EventEmitter<void>(); // Emits even to toglle sidebar

  onToggle() {
    this.toggleSidebar.emit(); // Emits the event to the parent when called
  }
}

<nav class="navbar">
  <div class="sticky">
    <div class="logo">
      <img src="/logo.svg" alt="icon" class="logoIcon" />
      <span>LinguaAI</span>
    </div>
    <ul class="ul">
      <li>
        <a routerLink="/" class="link" (click)="onToggle()"> Home </a>
      </li>
      <li>
        <a routerLink="/conversation" class="link" (click)="onToggle()">
          Conversation
        </a>
      </li>
      <li>
        <a routerLink="/about" class="link" (click)="onToggle()"> About </a>
      </li>
    </ul>
    <button *ngIf="isSidebarOpen" class="closeButton" (click)="onToggle()">
      X
    </button>
  </div>
</nav>

// react/src/components/Navbar.jsx
import styles from "./Navbar.module.css";
import { BrowserRouter as Router, Link } from "react-router-dom";
import logoIcon from "../../logo.svg";

function Navbar({ isSidebarOpen, toggleSidebar }) {
  return (
    <nav className={styles.navbar}>
      <div className={styles.sticky}>
        <div className={styles.logo}>
          <img src={logoIcon} alt="icon" className={styles.logoIcon} />
          <span>LinguaAI</span>
        </div>
        <ul className={styles.ul}>
          <li>
            <Link className={styles.link} to="/" onClick={toggleSidebar}>
              Home
            </Link>
          </li>
          <li>
            <Link
              className={styles.link}
              to="/conversation"
              onClick={toggleSidebar}
            >
              Conversation
            </Link>
          </li>
          <li>
            <Link className={styles.link} to="/about" onClick={toggleSidebar}>
              About
            </Link>
          </li>
        </ul>
        {isSidebarOpen && (
          <button className={styles.closeButton} onClick={toggleSidebar}>
            X
          </button>
        )}
      </div>
    </nav>
  );
}

export default Navbar;
