// react/src/pages/Conversation.jsx
import { useState, useEffect } from "react";
import axios from "axios";
import styles from "./Conversation.module.css";
import ChatMessage from "../components/ChatMessage";
import UserChatMessage from "../components/UserChatMessage";

function Conversation() {
  const apiUrl = "https://pronunciation-app.onrender.com";
  const [conversation, setConversation] = useState([]);
  const [inputValue, setInputValue] = useState("");

  // Fetch the entire conversation history when the component mounts
  async function fetchMessages() {
    try {
      const response = await axios.get("http://localhost:5000/messages");
      setConversation(response.data.messages);
    } catch (error) {
      console.error("Error fetching messages:", error);
    }
  }

  // Handle Enter key press to send the message
  function handleKeyPress(event) {
    if (event.key === "Enter") {
      handleSendMessage();
    }
  }

  // Handle seding a message
  async function handleSendMessage() {
    if (!inputValue.trim()) return; // Prevent sending empty messages

    try {
      const updatedConversation = [
        ...conversation,
        { role: "user", text: inputValue },
      ];

      const response = await axios.post("http://localhost:5000/conversation", {
        inputValue,
      });

      const aiMessage = { role: "ai", text: response.data };
      setConversation([...updatedConversation, aiMessage]);

      setInputValue("");
    } catch (error) {
      console.error("Error sending message:", error);
    }
  }

  // Fetch messages on component mount
  useEffect(() => {
    fetchMessages();
  }, []);

  return (
    <div className={styles.conversationDiv}>
      <div className={styles.container}>
        <div className={styles.chatContainer}>
          {/* Loop through the conversation and render messages */}
          {conversation.map((msg, index) =>
            msg.role === "ai" ? (
              <ChatMessage
                key={index}
                message={msg.text}
                className={styles.chatMessageAnimated}
              />
            ) : (
              <UserChatMessage
                key={index}
                message={msg.text}
                className={styles.userMessage}
              />
            )
          )}
        </div>

        {/* Input Field */}
        <div className={styles.inputDiv}>
          <div className={styles.innerInputDiv}>
            <input
              type="text"
              className={styles.input}
              placeholder="Type your message"
              value={inputValue}
              onChange={(e) => {
                setInputValue(e.target.value);
              }}
              onKeyDown={handleKeyPress}
            ></input>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Conversation;

// angular/src/app/pages/conversation/conversation.component.ts
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { ChatMessageComponent } from '../../components/chat-message/chat-message.component';
import { UserChatMessageComponent } from '../../components/user-chat-message/user-chat-message.component';
import { FormsModule } from '@angular/forms';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-conversation',
  standalone: true,
  imports: [
    CommonModule,
    HttpClientModule,
    ChatMessageComponent,
    UserChatMessageComponent,
    FormsModule,
  ],
  templateUrl: './conversation.component.html',
  styleUrl: './conversation.component.css',
})
export class ConversationComponent {
  apiUrl = environment.apiUrl;
  conversation: any = null;
  inputValue: string = '';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.fetchMessages();
  }

  fetchMessages(): void {
    try {
      this.http.get(`${this.apiUrl}/messages`).subscribe((response: any) => {
        console.log(response);
        this.conversation = response.messages;
        console.log(this.conversation);
      });
    } catch (error) {
      console.error('Error fetching messages', error);
    }
  }

  handleKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.handleSendMessage();
    }
  }

  async handleSendMessage() {
    if (!this.inputValue.trim()) return; // Prevent sending empty messages

    const updatedConversation = [
      ...this.conversation,
      { role: 'user', text: this.inputValue },
    ];

    try {
      const response: any = await this.http
        .post(`${this.apiUrl}/conversation`, {
          inputValue: this.inputValue,
        })
        .toPromise();
      const aiMessage = { role: 'ai', text: response };
      this.conversation = [...updatedConversation, aiMessage];

      // Clear the input field
      this.inputValue = '';
    } catch (error) {
      console.error('Error sending message:', error);
    }
  }

  // async function handleSendMessage() {
  //   if (!inputValue.trim()) return; // Prevent sending empty messages

  //   try {
  //     const updatedConversation = [
  //       ...conversation,
  //       { role: "user", text: inputValue },
  //     ];

  //     const response = await axios.post("http://localhost:5000/conversation", {
  //       inputValue,
  //     });

  //     console.log(response.data);
  //     const aiMessage = { role: "ai", text: response.data };
  //     setConversation([...updatedConversation, aiMessage]);

  //     setInputValue("");

  //     // fetchMessages();
  //   } catch (error) {
  //     console.error("Error sending message:", error);
  //   }
  // }
}

<div class="conversation-div">
  <div class="container">
    <div class="chat-container">
      <ng-container *ngFor="let msg of conversation; let msgIndex = index">
        <app-chat-message
          *ngIf="msg.role === 'ai'"
          [message]="msg.text"
          class="chat-message-animated"
        ></app-chat-message>
        <app-user-chat-message
          *ngIf="msg.role !== 'ai'"
          [message]="msg.text"
          class="user-message"
        ></app-user-chat-message>
      </ng-container>
    </div>
    <div class="input-div-conversation">
      <div class="inner-input-div">
        <input
          type="text"
          class="input-conversation"
          placeholder="Type your message"
          [(ngModel)]="inputValue"
          (keydown)="handleKeyPress($event)"
        />
      </div>
    </div>
  </div>
</div>
